postgres:
  image: mdillon/postgis:9.6
  restart: always
  ports: [5432:5432]
  environment: 
    POSTGRES_PASSWORD: example

pgadmin:
  image: dpage/pgadmin4
  environment:
    PGADMIN_DEFAULT_EMAIL: admin
    PGADMIN_DEFAULT_PASSWORD: admin
  ports:
    - 58368:80